CREATE TABLE `wx_user` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VERSION` bigint(20) DEFAULT NULL,
  `CREATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `OPENID` varchar(128) NOT NULL,
  `PHOTO_URL` varchar(512) DEFAULT NULL,
  `NICK_NAME` varchar(512) DEFAULT NULL,
  `ARTICLE_SHARE_COUNT` int(11) DEFAULT NULL,
  `CHANNEL` varchar(50) DEFAULT 'NORMAL',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `OPENID` (`OPENID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `wx_bind_user` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `OPENID` varchar(128) NOT NULL,
  `USER_ID` varchar(128) DEFAULT NULL,
  `LOGIN_NAME` varchar(128) DEFAULT NULL,
  `SYSTEM_CODE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
